# -*- coding: utf-8 -*-
"""ex2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H56HJSRrSIg65lPYmzuFDiA67chLNlhu
"""



import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression

# Load the dataset
data = pd.read_csv('headbrain.csv')

# Extract features and target
x = np.array(data['Head Size(cm^3)'])
y = np.array(data['Brain Weight(grams)'])

print(x[:5], y[:5])

# ---- Manual Linear Regression ----
def get_line(x, y):
    x_m, y_m = np.mean(x), np.mean(y)
    print("Mean of X and Y:", x_m, y_m)

    # Calculate slope (m) and intercept (c)
    x_d, y_d = x - x_m, y - y_m
    m = np.sum(x_d * y_d) / np.sum(x_d ** 2)
    c = y_m - (m * x_m)
    print("Slope (m):", m)
    print("Intercept (c):", c)

    # Return the line function
    return lambda x: m * x + c

lin = get_line(x, y)

# Generate predicted values for plotting
X = np.linspace(np.min(x) - 100, np.max(x) + 100, 1000)
Y = np.array([lin(i) for i in X])

# Plot
plt.scatter(x, y, color='green', label='Data points')
plt.plot(X, Y, color='red', label='Regression Line')
plt.xlabel('Head Size (cm³)')
plt.ylabel('Brain Weight (grams)')
plt.legend()
plt.show()

# ---- R² Error Calculation ----
def get_error(line_func, x, y):
    y_mean = np.mean(y)
    y_pred = np.array([line_func(i) for i in x])
    ss_total = np.sum((y - y_mean) ** 2)
    ss_res = np.sum((y - y_pred) ** 2)
    r2 = 1 - (ss_res / ss_total)
    return r2

print("Manual R² Score:", get_error(lin, x, y))

# ---- Using sklearn ----
x = x.reshape((len(x), 1))  # Reshape for sklearn
reg = LinearRegression()
reg.fit(x, y)

print("Sklearn Coefficient (m):", reg.coef_[0])
print("Sklearn Intercept (c):", reg.intercept_)
print("Sklearn R² Score:", reg.score(x, y))

