# -*- coding: utf-8 -*-
"""ex_10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2fn3em0aCbIqdjdKOPrpPYldCb9K-Nd
"""

from sklearn import datasets
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import seaborn as sns
iris = datasets.load_iris()
df = pd.DataFrame(iris['data'], columns = iris['feature_names'])
df.head()
scalar = StandardScaler()
scaled_data = pd.DataFrame(scalar.fit_transform(df)) #scaling the data
scaled_data
sns.heatmap(scaled_data.corr())
pca = PCA(n_components = 3)
pca.fit(scaled_data)
data_pca = pca.transform(scaled_data)
data_pca = pd.DataFrame(data_pca,columns=['PC1','PC2','PC3'])
data_pca.head()
sns.heatmap(data_pca.corr())