# -*- coding: utf-8 -*-
"""ex_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eIcv7EgSAjw09NUov9CffKo7hz5LULm5
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load dataset
bnotes = pd.read_csv('../input/banknotes-dataset/bank_note_data.csv')

# Split features and target
x = bnotes.drop('Class', axis=1)
y = bnotes['Class']

print(x.head(2))
print(y.head(2))

# ----------------------------------------
# Helper function to test different activations
# ----------------------------------------
def test_activation(test_ratio, activation_name):
    print("\n" + "="*70)
    print(f"Train-Test Split = {test_ratio}, Activation = {activation_name}")
    print("="*70)

    # split data
    x_train, x_test, y_train, y_test = train_test_split(
        x, y, test_size=test_ratio, random_state=42
    )

    # Train MLP
    mlp = MLPClassifier(max_iter=500, activation=activation_name)
    mlp.fit(x_train, y_train)

    # Predictions
    pred = mlp.predict(x_test)

    # Evaluation
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, pred))
    print("\nClassification Report:")
    print(classification_report(y_test, pred))


# =====================================================
# Test 1: train_test_ratio = 0.2 (20% test)
# =====================================================
for act in ["relu", "logistic", "tanh", "identity"]:
    test_activation(0.2, act)

# =====================================================
# Test 2: train_test_ratio = 0.3 (30% test)
# =====================================================
for act in ["relu", "logistic", "tanh", "identity"]:
    test_activation(0.3, act)