# -*- coding: utf-8 -*-
"""ex_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12bNUsUWwDl4UebYV9Pk10l9Gaq-TqS0U
"""

import numpy as np
import pandas as pd
from sklearn import svm
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(font_scale=1.2)

# Load dataset
recipes = pd.read_csv('../input/muffins-dataset/recipes_muffins_cupcakes.csv')

print(recipes.head())
print("Shape:", recipes.shape)

# Plot initial points
sns.lmplot(
    x='Sugar', y='Flour', data=recipes,
    hue='Type', palette='Set1',
    fit_reg=False, scatter_kws={'s': 70}
)

# Prepare features and labels
sugar_flour = recipes[['Sugar', 'Flour']].values
type_label = np.where(recipes['Type'] == 'Muffin', 0, 1)

# Train Linear SVM
model = svm.SVC(kernel='linear')
model.fit(sugar_flour, type_label)

# Extract model parameters
w = model.coef_[0]
intercept = model.intercept_[0]

# Equation of separating hyperplane
a = -w[0] / w[1]
xx = np.linspace(5, 30)
yy = a * xx - intercept / w[1]

# Plot support vectors
support_vectors = model.support_vectors_

# Margins
yy_down = a * xx + (support_vectors[0][1] - a * support_vectors[0][0])
yy_up = a * xx + (support_vectors[-1][1] - a * support_vectors[-1][0])

# Plot again with separators
sns.lmplot(
    x='Sugar', y='Flour', data=recipes,
    hue='Type', palette='Set1',
    fit_reg=False, scatter_kws={'s': 70}
)

plt.plot(xx, yy, color='black', linewidth=2)        # hyperplane
plt.plot(xx, yy_down, 'k--')                       # margin 1
plt.plot(xx, yy_up, 'k--')                         # margin 2

plt.scatter(
    support_vectors[:, 0], support_vectors[:, 1],
    s=80, facecolors='none', edgecolors='black'
)

plt.title("SVM Classification: Muffins vs Cupcakes")
plt.show()

# ---------------------------------------------------------
# Train-test split accuracy
# ---------------------------------------------------------

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

x_train, x_test, y_train, y_test = train_test_split(
    sugar_flour, type_label, test_size=0.2
)

model1 = svm.SVC(kernel='linear')
model1.fit(x_train, y_train)

pred = model1.predict(x_test)

print("\nPredicted labels:", pred)
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, pred))

print("\nClassification Report:")
print(classification_report(y_test, pred))