# -*- coding: utf-8 -*-
"""ex_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g4gHrdy-KVevP1uEk-bJxrizzFT70ozm
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier, plot_tree

# Load dataset
iris = load_iris()
X_all = iris.data
y_all = iris.target

# Parameters
n_classes = 3
plot_colors = ["r", "y", "b"]
plot_step = 0.02

# Feature pairs to plot
pairs = [[0, 1], [0, 2], [0, 3],
         [1, 2], [1, 3], [2, 3]]

plt.figure(figsize=(14, 8))

for idx, pair in enumerate(pairs):

    # Select only 2 features
    X = iris.data[:, pair]
    y = iris.target

    # Train Decision Tree
    clf = DecisionTreeClassifier().fit(X, y)

    # Create subplot
    plt.subplot(2, 3, idx + 1)

    # Define plot boundaries
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1

    xx, yy = np.meshgrid(np.arange(x_min, x_max, plot_step),
                         np.arange(y_min, y_max, plot_step))

    # Predict on mesh
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)

    # Plot decision boundary
    plt.contourf(xx, yy, Z, cmap=plt.cm.RdYlBu)

    # Plot training points
    for class_i, color in zip(range(n_classes), plot_colors):
        idxs = np.where(y == class_i)
        plt.scatter(X[idxs, 0], X[idxs, 1],
                    c=color, label=iris.target_names[class_i],
                    edgecolor="black", s=18)

    plt.xlabel(iris.feature_names[pair[0]])
    plt.ylabel(iris.feature_names[pair[1]])
    plt.title(f"Features: {pair[0]} vs {pair[1]}")
    plt.axis("tight")

plt.suptitle("Decision Surface of Decision Trees Trained on Feature Pairs", fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

# --------------------------------------------------------
# Plot Full Decision Tree Using All Features
# --------------------------------------------------------
plt.figure(figsize=(10, 8))
clf_full = DecisionTreeClassifier().fit(X_all, y_all)
plot_tree(clf_full, filled=True, feature_names=iris.feature_names,
          class_names=iris.target_names)
plt.title("Decision Tree Trained on All 4 Iris Features")
plt.show()