# -*- coding: utf-8 -*-
"""ex_8b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWfNnx47TXbw2X5GzVys2MnPcMSwLA9y
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeRegressor

# ----------------------------- #
#     GRADIENT BOOSTING CODE    #
# ----------------------------- #

def gradient_boost(X, y, n_estimators=5, lr=1.0):
    """
    Simple Gradient Boosting implementation using Decision Tree Regression.
    """

    models = []              # store learners
    pred_total = np.zeros_like(y)   # running prediction

    for i in range(n_estimators):

        # Residual = y - previous predictions
        residual = y - pred_total

        # Fit new tree on residuals
        tree = DecisionTreeRegressor(max_depth=5, random_state=42)
        tree.fit(X, residual)

        # Store the tree
        models.append(tree)

        # Update prediction
        pred_total += lr * tree.predict(X)

        # ---- Plotting each stage ----
        x_grid = np.linspace(-0.5, 0.5, 500).reshape(-1, 1)
        y_grid_pred = np.zeros(len(x_grid))

        for m in models:
            y_grid_pred += lr * m.predict(x_grid)

        print(f"Stage {i+1}")
        plt.figure(figsize=(6,4))
        plt.scatter(X, y, s=15, label="True y")
        plt.plot(x_grid, y_grid_pred, linewidth=2, label="Boosted Prediction")
        plt.title(f"Boosting Stage {i+1}")
        plt.legend()
        plt.show()

    return models



np.random.seed(42)
X = np.random.rand(100, 1) - 0.5
y = 3 * X[:, 0]**2 + 0.05 * np.random.randn(100)

models = gradient_boost(X, y, n_estimators=5, lr=1.0)