# -*- coding: utf-8 -*-
"""ex_8a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2tLft0m7rTOQGVSa8uk-wVoRfQbTE-c
"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from mlxtend.plotting import plot_decision_regions
import seaborn as sns
import matplotlib.pyplot as plt

# --------------------------------------------------------
# DATASET
# --------------------------------------------------------
df = pd.DataFrame()
df['X1'] = [1,2,3,4,5,6,6,7,9,9]
df['X2'] = [5,3,6,8,1,9,5,8,9,2]
df['label'] = [1,1,0,1,0,1,0,1,0,0]

sns.scatterplot(x=df['X1'], y=df['X2'], hue=df['label'])

# Initial weights
df['weights'] = 1/df.shape[0]

x = df[['X1','X2']].values
y = df['label'].values

# Convert labels {0,1} → {-1,+1}
y_signed = np.where(y==1, 1, -1)
df['y_signed'] = y_signed

# --------------------------------------------------------
# FUNCTION FOR MODEL WEIGHT
# --------------------------------------------------------
def calculate_alpha(error):
    return 0.5 * np.log((1-error) / error)

# --------------------------------------------------------
# ROUND 1
# --------------------------------------------------------
dt1 = DecisionTreeClassifier(max_depth=1)
dt1.fit(x, y_signed)

df['y_pred'] = dt1.predict(x)

# Compute error
error1 = (df['weights'] * (df['y_signed'] != df['y_pred'])).sum()
alpha1 = calculate_alpha(error1)

print("Alpha1 =", alpha1)

# Update weights
df['updated_weights'] = df['weights'] * np.exp(-alpha1 * df['y_signed'] * df['y_pred'])

# Normalize
df['norm_weights'] = df['updated_weights'] / df['updated_weights'].sum()

# Cumulative intervals for sampling
df['cumsum_upper'] = df['norm_weights'].cumsum()
df['cumsum_lower'] = df['cumsum_upper'] - df['norm_weights']

# --------------------------------------------------------
# FUNCTION FOR WEIGHTED SAMPLING
# --------------------------------------------------------
def sample_rows(df):
    indices = []
    for i in range(df.shape[0]):
        r = np.random.random()
        row = df[(df['cumsum_upper']>r) & (df['cumsum_lower']<=r)].index[0]
        indices.append(row)
    return indices

# --------------------------------------------------------
# ROUND 2
# --------------------------------------------------------
idx2 = sample_rows(df)
df2 = df.loc[idx2].copy()

x2 = df2[['X1','X2']].values
y2 = df2['y_signed'].values

dt2 = DecisionTreeClassifier(max_depth=1)
dt2.fit(x2, y2)

df2['y_pred'] = dt2.predict(x2)

error2 = (df2['norm_weights'] * (df2['y_signed'] != df2['y_pred'])).sum()
alpha2 = calculate_alpha(error2)

print("Alpha2 =", alpha2)

df2['updated_weights'] = df2['norm_weights'] * np.exp(-alpha2 * df2['y_signed'] * df2['y_pred'])
df2['norm_weights2'] = df2['updated_weights'] / df2['updated_weights'].sum()

# --------------------------------------------------------
# ROUND 3
# --------------------------------------------------------
idx3 = sample_rows(df2)
df3 = df2.loc[idx3].copy()

x3 = df3[['X1','X2']].values
y3 = df3['y_signed'].values

dt3 = DecisionTreeClassifier(max_depth=1)
dt3.fit(x3, y3)

df3['y_pred'] = dt3.predict(x3)

error3 = (df3['norm_weights2'] * (df3['y_signed'] != df3['y_pred'])).sum()
alpha3 = calculate_alpha(error3)

print("Alpha3 =", alpha3)
print("Boosting weights:", alpha1, alpha2, alpha3)

# --------------------------------------------------------
# FINAL BOOSTED PREDICTOR
# --------------------------------------------------------
def boosted_predict(x_query):
    p1 = dt1.predict(x_query)[0]
    p2 = dt2.predict(x_query)[0]
    p3 = dt3.predict(x_query)[0]
    final = np.sign(alpha1*p1 + alpha2*p2 + alpha3*p3)
    return final

# --------------------------------------------------------
# TEST QUERIES
# --------------------------------------------------------
q1 = np.array([1,5]).reshape(1,2)
print("\nQuery [1,5]:", boosted_predict(q1))

q2 = np.array([9,9]).reshape(1,2)
print("Query [9,9]:", boosted_predict(q2))