# -*- coding: utf-8 -*-
"""ex_9a.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1htmqxcmXJZSDvvZaShzXOLCxANGl-S-c
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans

# --------------------------- #
#    LOAD THE DATASET
# --------------------------- #
dataset = pd.read_csv("../input/mall-customers/Mall_Customers.csv")
X = dataset.iloc[:, [3, 4]].values   # Taking Annual Income & Spending Score
print(dataset.head())

# --------------------------- #
#    ELBOW METHOD
# --------------------------- #
wcss = []

for i in range(1, 11):
    kmeans = KMeans(
        n_clusters=i,
        init="k-means++",
        max_iter=300,
        n_init=10,
        random_state=0
    )
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)

# Plot Elbow Graph
plt.figure(figsize=(6, 4))
plt.plot(range(1, 11), wcss, marker='o')
plt.title("The Elbow Method")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.grid(True)
plt.show()

# --------------------------- #
#    APPLY K-MEANS (k = 5)
# --------------------------- #
kmeans = KMeans(
    n_clusters=5,
    init="k-means++",
    max_iter=300,
    n_init=10,
    random_state=0
)
y_kmeans = kmeans.fit_predict(X)

# --------------------------- #
#    VISUALIZE THE CLUSTERS
# --------------------------- #

plt.figure(figsize=(7, 5))

# Plot each cluster
plt.scatter(X[y_kmeans==0, 0], X[y_kmeans==0, 1], s=100, c='red', label='Cluster 1')
plt.scatter(X[y_kmeans==1, 0], X[y_kmeans==1, 1], s=100, c='blue', label='Cluster 2')
plt.scatter(X[y_kmeans==2, 0], X[y_kmeans==2, 1], s=100, c='green', label='Cluster 3')
plt.scatter(X[y_kmeans==3, 0], X[y_kmeans==3, 1], s=100, c='cyan', label='Cluster 4')
plt.scatter(X[y_kmeans==4, 0], X[y_kmeans==4, 1], s=100, c='magenta', label='Cluster 5')

# Plot the centroids
plt.scatter(
    kmeans.cluster_centers_[:, 0],
    kmeans.cluster_centers_[:, 1],
    s=300,
    c='yellow',
    edgecolor='black',
    label='Centroids'
)

plt.title("Clusters of Customers")
plt.xlabel("Annual Income (k$)")
plt.ylabel("Spending Score (1-100)")
plt.legend()
plt.show()